// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvMtYU28XpYd4qZkKX_4Z5UpvHrciBlcA',
    appId: '1:374797709988:web:ea5b07360892d69496ac31',
    messagingSenderId: '374797709988',
    projectId: 'lingualink-4d6e8',
    authDomain: 'lingualink-4d6e8.firebaseapp.com',
    storageBucket: 'lingualink-4d6e8.appspot.com',
    measurementId: 'G-MV4QFRRPTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIIX2vYzna5cP6fLtmLozSgj22X05ALtY',
    appId: '1:374797709988:android:0cc7883881522a3f96ac31',
    messagingSenderId: '374797709988',
    projectId: 'lingualink-4d6e8',
    storageBucket: 'lingualink-4d6e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IKWQ7CJhVyQRfVsTs0NWnAgdO-WimNk',
    appId: '1:374797709988:ios:42b003144ae67f4696ac31',
    messagingSenderId: '374797709988',
    projectId: 'lingualink-4d6e8',
    storageBucket: 'lingualink-4d6e8.appspot.com',
    iosBundleId: 'com.example.lingualink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IKWQ7CJhVyQRfVsTs0NWnAgdO-WimNk',
    appId: '1:374797709988:ios:42b003144ae67f4696ac31',
    messagingSenderId: '374797709988',
    projectId: 'lingualink-4d6e8',
    storageBucket: 'lingualink-4d6e8.appspot.com',
    iosBundleId: 'com.example.lingualink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvMtYU28XpYd4qZkKX_4Z5UpvHrciBlcA',
    appId: '1:374797709988:web:6b11d52bfc4b321296ac31',
    messagingSenderId: '374797709988',
    projectId: 'lingualink-4d6e8',
    authDomain: 'lingualink-4d6e8.firebaseapp.com',
    storageBucket: 'lingualink-4d6e8.appspot.com',
    measurementId: 'G-615S8JJDK2',
  );
}
